apiVersion: v2
name: team-a-service
description: A Helm chart for Team A Service - GitOps POC
type: application
version: 0.1.4
appVersion: "1.0.3"
keywords:
  - spring-boot
  - microservice
  - gitops
  - team-a
home: https://github.com/Duggireddy-NSF/team-a-service
sources:
  - https://github.com/Duggireddy-NSF/team-a-service
maintainers:
  - name: Team A
    email: team-a@example.com
annotations:
  category: Application
